module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'introduction',
        'getting-started',
        'controlled-vs-uncontrolled',
        'editing-mode',
        'persistence',
        'usage-examples',
        'faq',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api'
        }
      ],
    },
  ],
};

